version: "2"

services:

  dev:
    image: kevineye/vis-api:dev
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development

  shell:
    extends:
      service: app
    entrypoint: bash
